hosts/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.views.generic import list_detail, ListView, DetailView
from hosts.models import *
from hosts.views import *
from datetime import date,timedelta

# return an queryset of 'Host', if we ask for a list default is --> template/hosts/host_list.html
# return an queryset of 'Host', if we ask for a detail default is --> template/hosts/host_detail.html
def get_hosts():
    return {'queryset': Host.objects.all()}

# return an queryset of 'Client', if we ask for a list default is --> template/hosts/client_list.html
# return an queryset of 'Client', if we ask for a detail default is --> template/hosts/client_detail.html
def get_clients():
    return {'queryset': Client.objects.all().order_by('clientname')}

# return an queryset of 'Vlan', if we ask for a list default is --> template/hosts/vlan_list.html
# return an queryset of 'Vlan', if we ask for a detail default is --> template/hosts/vlan_detail.html
def get_vlans():
    return {'queryset': Vlan.objects.all()}

# return an queryset of 'OS', if we ask for a list default is --> template/hosts/os_list.html
# return an queryset of 'OS', if we ask for a detail default is --> template/hosts/os_detail.html
def get_oses():
    return {'queryset': OS.objects.all().order_by('osname', 'vendor', 'majorversion', 'minorversion')}

# return an queryset of 'Package', if we ask for a list default is --> template/hosts/package_list.html
# return an queryset of 'Package', if we ask for a detail default is --> template/hosts/package_detail.html
def get_pkgs():
    return { 'queryset' : Package.objects.all().order_by('pkgname', '-version') }


# Reporting:

# produce a list of servers without package ILMT-TAD4D-agent installed
# return an queryset of 'Host', we ask for a list default is --> template/hosts/host_list.html
def get_no_imlt():
    return { 
      'queryset' : Host.objects.exclude(packages__pkgname__contains="ILMT-TAD4D-agent"),
      'extra_context': {'title': 'Hosts without ILMT', 'h2': 'Hosts without ILMT'},
    }

# produce a list of servers where lastchek is greater than 7 days
# return an queryset of 'Host', we ask for a list default is --> template/hosts/host_list.html
def get_old_check():
    return {
      'queryset' : Host.objects.exclude(lastcheck__range=(date.today() - timedelta(7), date.today())),
      'extra_context': {'title': 'Old check', 'h2': 'Outdated inventories'},
    }

urlpatterns = patterns('hosts.views',
    (r'^$', direct_to_template, {'template': 'hosts/index.html'}),
    #(r'^hosts/$', 'hosts'),
    #(r'^hosts/(?P<sortby>\w+)/$', 'hosts'),
    (r'^hosts/host/(?P<object_id>\d+)/$', list_detail.object_detail, get_hosts()),
    (r'^hosts/host/update/(?P<pk>\d+)/$', UpdateHost.as_view()),
    (r'^search/(?P<searchclass>.*)/(?P<searchvalue>.*)/$', 'searchview'),
    (r'^reporting/oldinv/$', list_detail.object_list, get_old_check()),
    (r'^clients/$', list_detail.object_list, get_clients()),
    (r'^clients/client/(?P<object_id>\d+)/$', list_detail.object_detail, get_clients()),
    (r'^clients/client/update/(?P<pk>\d+)/$', UpdateClient.as_view()),
    (r'^vlans/$', ListView.as_view(model = Vlan)),
    (r'^vlans/vlan/(?P<pk>\d+)/$', DetailView.as_view(model=Vlan)),
    (r'^vlans/update/vlan/(?P<pk>\d+)/$', UpdateVlan.as_view()),
    (r'^oses/$', list_detail.object_list, get_oses()),
    (r'^oses/type/(?P<os_type>\w+)/$', 'ostype'),
    (r'^oses/vendor/(?P<os_vendor>\w+)/$', 'osvendor'),
    (r'^oses/os/(?P<object_id>\d+)/$', list_detail.object_detail, get_oses()),
    #(r'^packages/allpackages/$', 'get_all_packages'),
    (r'^packages/no_ilmt/$', list_detail.object_list, get_no_imlt()),
    (r'^packages/package/(?P<object_id>\d+)/$', list_detail.object_detail, get_pkgs()),
    (r'^addremovehost/$','addremovehost'),
    (r'^addhost/$','addhost'),
    (r'^removehost/$','removehost'),
)
#    (r'^vlans/$', list_detail.object_list, get_vlans()),
#    (r'^vlans/vlan/(?P<object_id>\d+)/$', list_detail.object_detail, get_vlans()),

urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

from django.contrib import databrowse
from hosts.models import *
databrowse.site.register(Host)
databrowse.site.register(Client)
databrowse.site.register(OS)
databrowse.site.register(Package)
databrowse.site.register(User)
databrowse.site.register(Group)
databrowse.site.register(Vlan)
databrowse.site.register(Disk)
databrowse.site.register(HostGroup)

from django.conf import settings

urlpatterns = patterns('',
    (r'^$', include('web.urls')),
    (r'^hosts/', include('hosts.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^db/(.*)', databrowse.site.root),
    (r'^logs/', 'web.views.logs'),
    (r'^lookup/$', 'web.views.resolv'),
)

hosts/models.py
from django.db import models

class Host(models.Model):
    hostname = models.CharField(max_length=40, unique=True)
    description = models.TextField(null=True,blank=True)
    uptime = models.IntegerField(null=True,blank=True)
    client = models.ForeignKey('Client',null=True,blank=True)
    os = models.ForeignKey('OS')
    HOSTS_TYPES = (('Physical', 'Physical'),('Virtual', 'Virtual'))
    type = models.CharField(max_length=10,choices=HOSTS_TYPES,null=True,blank=True)
    cpu = models.IntegerField() # number of cores
    gbmem = models.DecimalField(max_digits=8,decimal_places=1)
    vlan = models.ForeignKey('Vlan',null=True,blank=True)
    ip = models.IPAddressField(unique=True) # admin ip (should be in dns)
    packages = models.ManyToManyField('Package', related_name='hosts')
    lastcheck = models.DateField(null=True,blank=True) # last inventory
    lastupdate = models.DateField(null=True,blank=True) # last os update
    datediff = models.IntegerField(null=True,blank=True) # seconds between this host and inventory server
    class Meta:
        ordering = ['hostname']
    def getent(self):
        for u in self.user_set.all():
            print u.getent()
    def __unicode__(self):
        return self.hostname

class HostGroup(models.Model):
    hostgroupname = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=50)
    members = models.ManyToManyField('Host', related_name='hostgroups', null=True, blank=True)
    class Meta:
        ordering = ['hostgroupname']
    def __unicode__(self):
        return self.hostgroupname


class Client(models.Model):
    clientname = models.CharField(max_length=50, unique=True)
    class Meta:
        ordering = ['clientname']
    def __unicode__(self):
        return self.clientname

class OS(models.Model):
    osname = models.CharField(max_length=15)
    vendor = models.CharField(max_length=15)
    majorversion = models.CharField(max_length=15)
    minorversion = models.CharField(max_length=15)
    class Meta:
        ordering = ['vendor', 'majorversion', 'minorversion']
    def __unicode__(self):
        if (self.osname == 'Linux'):
            return self.vendor + " " + self.majorversion + "." + self.minorversion
        elif(self.osname == 'Solaris'):
            return self.osname + " " + self.majorversion + "u" + self.minorversion
        else:
            return self.osname + " " + self.majorversion + " " + self.minorversion

class Vlan(models.Model):
    vlannumber = models.IntegerField()
    vlanname = models.CharField(max_length=40)
    network = models.IPAddressField(unique=True)
    netmask = models.IPAddressField()
    gateway = models.IPAddressField(null=True, blank=True)
    dns1 = models.IPAddressField(null=True, blank=True)
    dns2 = models.IPAddressField(null=True, blank=True)
    domain = models.CharField(max_length=40,null=True, blank=True)
    ntp = models.CharField(max_length=40,null=True, blank=True)
    class Meta:
        ordering = ['vlannumber']
    def __unicode__(self):
        return str(self.vlannumber) + " - " + self.vlanname + ' - ' + self.network + " - " + self.netmask
    
class Disk(models.Model):
    diskname = models.CharField(max_length = 50)
    size = models.IntegerField()
    deviceid = models.CharField(max_length = 4, null=True, blank=True)
    host = models.ForeignKey('Host')
    def __unicode__(self):
        return self.diskname
    class Meta:
        ordering = ['host__hostname','diskname']

class Group(models.Model):
    groupname = models.CharField(max_length = 40)
    gid = models.IntegerField()
    host = models.ForeignKey('Host')
    members = models.ManyToManyField('User', related_name='groups')
    extmembers = models.ManyToManyField('ExternalUser', related_name='intgroups')
    class Meta:
        ordering = ['gid']
    def __unicode__(self):
        return self.groupname

class AbsUser(models.Model):
    username = models.CharField(max_length = 40, default="")
    uid = models.IntegerField()
    gid = models.IntegerField()
    gecos = models.CharField(max_length = 70, null=True, blank=True)
    home = models.CharField(max_length = 200, default="")
    shell = models.CharField(max_length = 70, default="")
    def getent(self):
        out =  "%s:x:%s:%s:%s:%s:%s" % (self.username, self.uid, self.gid, self.gecos, self.home, self.shell)
        return out.encode("latin1")
    class Meta:
        abstract = True
    def __unicode__(self):
        return self.username

class ExternalUser(AbsUser):
    class Meta:
        ordering = ['username']

class User(AbsUser):
    host = models.ForeignKey('Host')
    class Meta:
        ordering = ['host','uid']

class Package(models.Model):
    pkgname = models.CharField(max_length = 100)
    version = models.CharField(max_length = 50)
    class Meta:
        ordering = ['pkgname','version']
    def __unicode__(self):
        return self.pkgname

class FStype (models.Model):
    fstype = models.CharField(max_length = 40)
    description = models.CharField(max_length = 40)
    class Meta:
        ordering = ['fstype']
    def __unicode__(self):
        return self.fstype

class FS(models.Model):
    device = models.CharField(max_length = 40)
    fstype = models.ForeignKey('FStype')
    size = models.DecimalField(max_digits=8,decimal_places=1)
    percent_used = models.IntegerField()
    mountpoint = models.CharField(max_length = 40)
    host = models.ForeignKey('Host')
    def get_size_gb(self):
        return "%.2f" % (self.size/1024)
    class Meta:
        ordering = ['host__hostname','mountpoint']
    def __unicode__(self):
        return self.mountpoint

class Interface (models.Model):
    INTERFACE_TYPES = (('NET','NET'),('FC','FC'))
    name = models.CharField(max_length=30) # eth0, etc
    type = models.CharField(max_length='10', choices=INTERFACE_TYPES)
    hwaddr = models.CharField(max_length=32) # mac, wwn
    ips = models.ManyToManyField('IP', related_name='interfaces', null=True, blank=True)
    host = models.ForeignKey('Host')
    linkstate = models.BooleanField() # True == Up, False == Down
    speed = models.CharField(max_length=32) # 'autoneg full-duplex 1GB' or '8GB'
    extra = models.CharField(max_length=50) # slaves if bonding or etherchannel
    class Meta:
        ordering = ['host', 'name']
    def __unicode__(self):
        return "%s_%s" % (self.host,self.name)

class IP (models.Model):
    ipaddr = models.CharField(max_length=40) # ip v4 ou v6
    netmask = models.CharField(max_length=40) # ip v4 ou v6
    class Meta:
        ordering = ['ipaddr']
    def __unicode__(self):
        return self.ipaddr

class Daemon (models.Model):
    name = models.CharField(max_length=40) # ntpd par ex
    #is_running = models.BooleanField() # True si il tourne effectivement
    hosts = models.ManyToManyField('Host',related_name='daemons', null=True, blank=True)
    class Meta:
        #ordering = ['is_running','name']
        ordering = ['name']
    def __unicode__(self):
        return self.name

class Netlink(models.Model):
    local_ip = models.CharField(max_length=40) # ip
    local_port = models.IntegerField() # port
    remote_ip = models.CharField(max_length=40) # ip
    remote_port = models.IntegerField() # port
    host = models.ForeignKey('Host',related_name='netlinks')
    def get_direction(self):
      '''TODO: implement direction detector'''
      return "<?>"
    class Meta:
        ordering = ['local_ip','local_port','remote_ip']
    def __unicode__(self):
        return "%s:%s %s %s:%s" % (local_ip,local_port,self.get_direction(),remote_ip,remote_port)

# not yet implemented in scritps
class AppCatalog(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=50)
    script = models.TextField()
    class Meta:
        ordering = ['name']
    def __unicode__(self):
        return self.name

class Application(models.Model):
    application = models.ForeignKey('AppCatalog')
    version = models.CharField(max_length = 50, null = True, blank = True)
    appdir = models.CharField(max_length = 50, null = True, blank = True)
    hosts = models.ManyToManyField('Host', related_name='applications', null=True, blank=True)
    class Meta:
        ordering = ['application', 'version']
    def __unicode__(self):
        return self.application.name

hosts/forms.py
from django import forms
from hosts.models import Client, Host, Vlan

class AddHostForm(forms.Form):
  hostname = forms.CharField(max_length=40, label="Hostname")
  client = forms.ModelChoiceField(queryset=Client.objects.all().order_by('clientname'), label="Client")

class DeleteHostForm(forms.Form):
  host = forms.ModelChoiceField(queryset=Host.objects.all().order_by('hostname'), label="Host to remove")

class VlanForm(forms.ModelForm):
  class Meta:
    model = Vlan

class ClientForm(forms.ModelForm):
  class Meta:
    model = Client

class HostForm(forms.ModelForm):
  class Meta:
    model = Host
    exclude = ('packages',)

templates/hosts/client_detail.html
{% extends "base.html" %}

{% block title %}Client {{object}}{% endblock %}

{% block content %}
<a href="../..">[..]</a>
<div class="hero-unit">
<h2>{{object}} ({{object.host_set.count}})</h2>
<a href="/hosts/clients/client/update/{{object.pk}}/">Edit</a>
</div>
{% with hosts=object.host_set.all %}
{% include 'hosts/hosts_table.html' %}
{% endwith %}
{% endblock %}

templates/hosts/client_form.html
{% extends "base.html" %}

{% block title %}Update Client{% endblock %}

{% block content %}
<div class="hero-unit">                              
<h2>Update Client</h2>                     
</div>                                               
<form action="" method="post"> {%csrf_token%}
<table class="zebra-striped">
{{form.as_table}}
</table>
<input type="submit" value="Update" />
</form>
{% endblock %}

templates/hosts/client_list.html
{% extends "base.html" %}

{% block title %}Clients{% endblock %}

{% block content %}
{% if object_list %}
<div class="hero-unit">
<h2>Clients ({{object_list.count}})</h2>
<p>Here a list of all clients known by Inventory!</p>
<p>Clic on a field to go to more details.</p>      
</div>
<table class="zebra-striped">
<thead>
<tr>
  <th>Client Name</th>
  <th>Hosts</th>
</tr>
</thead>
<tbody>
{% for client in object_list %}
  <tr><td><a href='/hosts/clients/client/{{client.id}}/'>{{client}}</a></td><td>{{client.host_set.count}}</td></tr>
{% endfor %}
</tbody>
</table>
</div>
{% else %}
<h1 style="color:#D92828">No Clients in db</h1>
{% endif %}
{% endblock %}

templates/hosts/host_detail.html
{% extends "base.html" %}

{% block title %}Host {{object}}{% endblock %}

{% block content %}
{% if object %}
<a href="../..">[..]</a>
<div class="hero-unit">
<h2>{{object.hostname}}</h2>
<h3>{{object.description}}</h3>
<table class="zebra-striped">
<tr><th>Client</th><td><a href='/hosts/clients/client/{{object.client.id}}/'>{{object.client}}</a></td></tr>
<tr><th>OS</th><td><a href='/hosts/oses/os/{{object.os.id}}/'>{{object.os}}</a></td></tr>
<tr><th>Type</th><td>{{object.type}}</td></tr>
<tr><th>CPUs</th><td>{{object.cpu}}</td></tr>
<tr><th>Mem</th><td>{{object.gbmem}}</td></tr>
<tr><th>Vlan</th><td><a href='/hosts/vlans/vlan/{{object.vlan.id}}/'>{{object.vlan}}</a></td></tr>
<tr><th>IP</th><td>{{object.ip}}</td></tr>
<tr><th>Last inventory</th><td>{{object.lastcheck}}</td></tr>
<tr><th>Last Full Backup</th><td>TBI</td></tr>
<tr><th>Last Update</th><td>{{object.lastupdate}}</td></tr>
</table>
<a href="/hosts/hosts/host/update/{{object.pk}}/">Edit</a>
</div>
<p>
<h3>Disks ({{object.disk_set.count}})</h3>
<table class="zebra-striped">
<thead>
<tr><th>Disk name</th><th>Size</th></tr>
</thead>
<tbody>
{% for d in object.disk_set.all %}
  <tr><td>{{d.diskname}}</td><td>{{d.size}}GB</td></tr>
{% endfor %}
</tbody>
</table>
</p>
<!-- Filesystems -->
<p>
<h3>FileSystems ({{object.fs_set.count}})</h3>
<table class="zebra-striped">
<thead>
<tr>
  <th>Device</th> <th>Type</th> <th>Size</th> <th>%Used</th> <th>Mountpoint</th>
</tr>
</thead>
<tbody>
{% for fs in object.fs_set.all %}
<tr>
    <td>{{fs.device}}</td> <td>{{fs.fstype}}</td> <td>{{fs.get_size_gb}}</td> <td>{{fs.percent_used}}</td> <td>{{fs.mountpoint}}</td>
</tr>
{% endfor%}
</tbody>
</table>
</p>
<!-- /end Filesystems -->
<p>
<h3>Users ({{object.user_set.count}})</h3>
<table class="zebra-striped">
<thead>
<tr>
  <th>uid</th> <th>username</th> <th>gid</th> <th>gecos</th> <th>home</th> <th>shell</th>
</tr>
</thead>
<tbody>
{% for u in object.user_set.all %}
  <tr><td>{{u.uid}}</td><td><a href="/hosts/search/user/{{u}}">{{u}}</a></td><td>{{u.gid}}</td><td>{{u.gecos}}</td><td>{{u.home}}</td><td>{{u.shell}}</td></tr>
{% endfor %}
</tbody>
</table>
</p>
<p>
<h3>Groups ({{object.group_set.count}})</h3>
<table class="zebra-striped">
<thead>
<tr>
  <th>gid</th>
  <th>group name</th>
  <th>users</th>
</tr>
</thead>
<tbody>
{% for g in object.group_set.all %}
  <tr><td>{{g.gid}}</td><td>{{g}}</td><td>
  {% if g.members.count > 0 %}
    {% for m in g.members.all %}{{m}} {% endfor  %}
  {% else %}
    &nbsp;
  {%endif%}
  </td>
{% endfor %}
</tbody>
</table>
</p>
<p>
<h3>Packages ({{object.packages.count}})</h3>
<table class="zebra-striped">
<thead>
<tr>
  <th>Package Name</th>
  <th>Version</th>
</tr>
</thead>
<tbody>
{% for p in object.packages.all %}
  <tr><td><a href='/hosts/search/package/{{p}}/'>{{p}}</a></td><td>{{p.version}}</td></tr>
{% endfor %}
</tbody>
</table>
</p>
{% else %}
TODO: mettre une image de Peugeot 404
{% endif %}
{% endblock %}

templates/hosts/host_form.html
{% extends "base.html" %}

{% block title %}Update Host{% endblock %}

{% block content %}
<div class="hero-unit">                              
<h2>Update Host</h2>                     
</div>                                               
<form action="" method="post"> {%csrf_token%}
<table class="zebra-striped">
{{form.as_table}}
</table>
<input type="submit" value="Update" />
</form>
{% endblock %}

templates/hosts/hosts.html
{% extends "base.html" %}

{% block title %}Hosts{% endblock %}

{% block content %}
{% if hosts %}
<div class="hero-unit">
<h2>Hosts ({{hosts.count}})</h2>
<p>Here a list of all hosts known by Inventory!</p>
<p>Clic on a field to go to more details.</p>
</div>
{%include 'hosts/hosts_table.html' %}
{% else %}
<h1 style="color:#D92828">No hosts in db</h1>
{% endif %}
{% endblock %}

templates/hosts/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="hero-unit">                              
<h2>All about hosts and so on</h2>                     
</div>                                               
{% endblock %}

templates/hosts/os_detail.html
{% extends "base.html" %}

{% block title %}OS {{object}}{% endblock %}

{% block content %}
<a href="../..">[..]</a>
<div class="hero-unit">
<h2>{{object}}</h2>
<table class="zebra-striped">
<tr><th>Type</th><td><a href='/hosts/oses/type/{{object.osname}}/'>{{object.osname}}</a></td></tr>
<tr><th>Vendor</th><td><a href='/hosts/oses/vendor/{{object.vendor}}/'>{{object.vendor}}</a></td></tr>
<tr><th>Major</th><td>{{object.majorversion}}</td></tr>
<tr><th>Minor</th><td>{{object.minorversion}}</td></tr>
</table>
</div>
{% with hosts=object.host_set.all %}
{% include 'hosts/hosts_table.html' %}
{% endwith%}
{% endblock %}

templates/hosts/os_list.html
{% extends "base.html" %}

{% block title %}OSes{% endblock %}

{% block content %}
{% if object_list %}
<div class="hero-unit"> 
<h2>OSes ({{object_list.count}})</h2>
<p>Here a list of all OS known by Inventory!</p>
<p>Clic on a field to go to more details.</p>      
</div>
<table class="zebra-striped">
<thead>
<tr>
  <th>Type</th>
  <th>Vendor</th>
  <th>Full name</th>
  <th>Hosts</th>
</tr>
</thead>
<tbody>
{% for os in object_list %}
  <tr>
    <td><a href='/hosts/oses/type/{{os.osname}}/'>{{os.osname}}</a></td>
    <td><a href='/hosts/oses/vendor/{{os.vendor}}/'>{{os.vendor}}</a></td>
    <td><a href='/hosts/oses/os/{{os.id}}/'>{{os}}</a></td>
    <td>{{os.host_set.count}}</td>
  </tr>
{% endfor %}
</tbody>
</table>
{% else %}
<h1 style="color:#D92828">No Clients in db</h1>
{% endif %}
{% endblock %}

templates/hosts/os_type.html
{% extends "base.html" %}

{% block title %}{{type}}{% endblock %}

{% block content %}
<a href="../..">[..]</a>
<div class="hero-unit">
<h2>{{type}} ({{oses.count}})</h2>
<p>Here all versions of {{type}} declined by major and minor versions.</p>
<p>Clic on a field for more details.</p>
</div>
<table class="zebra-striped">
<thead>
<tr><th>Versions</th><th>Hosts</th></tr>
</thead>
<tbody>
{% for os in oses %}
  <tr>
    <td><a href='/hosts/oses/os/{{os.id}}/'>{{os}}</a></td>
    <td>{{os.host_set.count}}</td>
  </tr>
{%endfor%}
</tbody>
</table>

<table class="zebra-striped">
<thead>
<tr><th>Hosts</th><th>OS</th></tr>
</thead>
<tbody>
</tbody>
  {%for os in oses%}
    {%for h in os.host_set.all%}
    <tr>
      <td><a href='/hosts/hosts/host/{{h.id}}'>{{h}}</a></td>
      <td><a href='/hosts/oses/os/{{h.os.id}}/'>{{h.os}}</a></td>
    </tr>
    {%endfor%}
  {%endfor%}
</tbody>
</table>
{% endblock %}

templates/hosts/package_list.html
{% extends "base.html" %}

{% block title %}Packages{% endblock %}

{% block content %}
{% if current_page_paginator %}
<div class="hero-unit">
<h2>Packages ({{current_page_paginator.paginator.count}})</h2>
<p>Here a list of all packages known by Inventory!</p>
<p>Clic on a field to go to more details.</p>      
</div>                                             
<div class=row>
<table class="zebra-striped" id="PackageTable">
<thead>
<tr>
  <th>Package Name</th>
  <th>Version</th>
  <th>Hosts</th>
</tr>
</thead>
<tbody>
{% for p in current_page_paginator.object_list %}
  <tr><td><a href='/hosts/packages/package/{{p.id}}/'>{{p}}</a></td><td>{{p.version}}</td><td>{{p.hosts.count}}</td></tr>
{% endfor %}
</tbody>
</table>
</div>
{% else %}
<h1 style="color:#D92828">No Packages in db</h1>
{% endif %}

{% include "bottom_paginator.html" %}
{% endblock %}

templates/hosts/vlan_detail.html
{% extends "base.html" %}

{% block title %}Vlan {{object.vlannumber}} {{object.vlanname}}{% endblock %}

{% block content %}
<a href="../..">[..]</a>
<div class="hero-unit">
<h2>Vlan {{object.vlannumber}} / {{object.vlanname}}</h2>
<table class="zebra-striped">
<tr><th>Network</th><td>{{object.network}}</td></tr>
<tr><th>Netmask</th><td>{{object.netmask}}</td></tr>
<tr><th>gateway</th><td>{{object.gateway}}</td></tr>
<tr><th>dns1</th><td>{{object.dns1}}</td></tr>
<tr><th>dns2</th><td>{{object.dns2}}</td></tr>
<tr><th>domain</th><td>{{object.domain}}</td></tr>
<tr><th>ntp</th><td>{{object.ntp}}</td></tr>
</table>
<a href="/hosts/vlans/update/vlan/{{object.pk}}/">Edit</a>
</div>
{% with hosts=object.host_set.all %}
{% include 'hosts/hosts_table.html' %}
{% endwith%}
{% endblock %}

templates/hosts/vlan_form.html
{% extends "base.html" %}

{% block title %}Update Vlan{% endblock %}

{% block content %}
<div class="hero-unit">                              
<h2>Update Vlan</h2>                     
</div>                                               
<form action="" method="post"> {%csrf_token%}
<table class="zebra-striped">
{{form.as_table}}
</table>
<input type="submit" value="Update" />
</form>
{% endblock %}

templates/hosts/vlan_list.html
{% extends "base.html" %}

{% block title %}Vlans{% endblock %}

{% block content %}
{% if object_list %}
<div class="hero-unit">
<h2>Vlans ({{object_list.count}})</h2>
<p>Here a list of all vlans known by Inventory!</p>
<p>Clic on a field to go to more details.</p>      
</div>                                             
<script>
$(document).ready(function()
{
  $("#VlanTable").tablesorter();
});
</script>
<table class="zebra-striped" id="VlanTable">
<thead>
<tr>
  <th>Num</th>
  <th>Name</th>
  <th>Network</th>
  <th>NetMask</th>
  <th>GateWay</th>
  <th>DNS</th>
  <th>Hosts</th>
</tr>
</thead>
<tbody>
{% for vlan in object_list %}
  <tr>
    <td><a href='/hosts/vlans/vlan/{{vlan.id}}/'>{{vlan.vlannumber}}</a></td>
    <td><a href='/hosts/vlans/vlan/{{vlan.id}}/'>{{vlan.vlanname}}</a></td>
    <td>{{vlan.network}}</td>
    <td>{{vlan.netmask}}</td>
    <td>{{vlan.gateway}}</td>
    <td>{{vlan.dns1}}</td>
    <td><a href='/hosts/vlans/vlan/{{vlan.id}}/'>{{vlan.host_set.count}}</a></td>
  </tr>
{% endfor %}
</tbody>
</table>
</div>
{% else %}
<h1 style="color:#D92828">No Vlans in db</h1>
{% endif %}
{% endblock %}